In [1]:
import  numpy as np

In [2]:
N = 100
D = 2

X = np.random.randn(N,D)

In [3]:
ones = np.array([[1]*N]).T

In [8]:
Xb = np.concatenate((ones,X), axis=1)
Xb

array([[ 1.        , -0.65514294, -0.42801678],
       [ 1.        ,  0.64553013, -0.80057922],
       [ 1.        ,  0.19424777,  2.02294237],
       [ 1.        , -0.074572  ,  1.93103962],
       [ 1.        ,  0.03327921,  0.79760636],
       [ 1.        , -0.96179537,  0.04825449],
       [ 1.        ,  0.06240264, -0.54027733],
       [ 1.        , -0.9797637 ,  1.48171195],
       [ 1.        , -1.32329865,  1.39030482],
       [ 1.        ,  0.33219771,  0.42747309],
       [ 1.        , -1.09900025,  1.84147038],
       [ 1.        ,  1.38349648,  0.81150071],
       [ 1.        , -0.5295045 , -1.2196042 ],
       [ 1.        ,  1.04925547,  0.59901427],
       [ 1.        , -0.22265946, -0.75082919],
       [ 1.        ,  1.29509582,  1.1120558 ],
       [ 1.        , -1.33376123,  0.73117985],
       [ 1.        ,  1.35303117, -1.77680658],
       [ 1.        , -0.195908  ,  1.01239545],
       [ 1.        , -0.10667771, -0.11959202],
       [ 1.        ,  0.51819693,  1.789

In [9]:
w = np.random.randn(D+1)
w

array([ 0.52482629, -2.01496621, -0.84771468])

In [11]:
z = Xb.dot(w)
z

array([ 2.20775328e+00, -9.72323519e-02, -1.58145435e+00, -9.61884279e-01,
       -2.18372803e-01,  2.42190543e+00,  8.57088104e-01,  1.24294808e+00,
        2.01264656e+00, -5.06916074e-01,  1.17823320e+00, -2.95079343e+00,
        2.62563636e+00, -2.09718122e+00,  1.60996650e+00, -3.02745405e+00,
        2.59247822e+00, -6.95260785e-01,  6.13518140e-02,  8.41158193e-01,
       -2.03599347e+00, -2.19897876e+00,  1.30289569e+00, -8.70392861e-02,
       -1.44452130e-01, -6.63015517e-01,  3.49927490e+00,  8.12606536e-01,
        2.77679772e+00,  3.00779552e+00,  3.06217994e-02,  1.66967374e+00,
        1.15051052e+00,  5.06088794e-01,  4.40511130e+00, -3.19778390e+00,
        3.47773841e+00,  5.59191815e+00,  1.62025651e+00,  2.56066503e+00,
        1.67633553e+00, -2.20815751e+00,  9.14919434e-01, -5.33397643e-01,
       -1.22682786e+00, -3.30399762e+00, -1.94099458e+00,  1.37946451e+00,
        1.56577866e+00,  4.24702729e-01,  8.64987300e-03, -7.43384697e-01,
        1.02701554e+00,  

In [12]:
def sigmoid(z):
    return  1/ (1 + np.exp(-z))

print(sigmoid(z))

[0.9009436  0.47571104 0.17058961 0.27650109 0.44562272 0.91848252
 0.70205192 0.77607675 0.8821185  0.37591675 0.76462998 0.04969903
 0.93249338 0.10937109 0.83340674 0.04620089 0.93037592 0.33286381
 0.51533314 0.69870909 0.11547533 0.09984223 0.78632192 0.47825391
 0.46394963 0.34006254 0.97066713 0.69266466 0.94140906 0.95292506
 0.50765485 0.84153232 0.75960415 0.62388915 0.98793265 0.0392492
 0.97004768 0.99628598 0.8348305  0.92828674 0.84241868 0.09902033
 0.71400578 0.36972479 0.22673711 0.0354343  0.12553863 0.79890499
 0.82718099 0.60460802 0.50216245 0.32226445 0.73633689 0.66085791
 0.08137192 0.91519093 0.9676762  0.99579433 0.67698044 0.01308614
 0.53567562 0.36660585 0.66450045 0.53932293 0.4354178  0.2055384
 0.76438259 0.95983833 0.65891825 0.86082324 0.78327195 0.29596241
 0.23827788 0.80992415 0.11241358 0.30646737 0.27403117 0.73388563
 0.22063273 0.68614301 0.70755484 0.65081341 0.37793985 0.8393773
 0.40679262 0.28532377 0.00702481 0.20541803 0.73566683 0.5012518