In [74]:
import numpy as np
import pandas as pd
import os
os.getcwd()


'/home/o/python3/untitled'

In [64]:
def get_data():
    df = pd.read_csv("./data/ecommerce_data.csv")
    data = df.values
    
    X = data[:, : -1]
    Y = data[:, -1]
    
    X[:,1] = (X[:,1] - X[:,1].mean() ) / X[:,1].std()
    X[:,2] = (X[:,2] - X[:,2].mean() ) / X[:,2].std()
    
    N, D = X.shape
    X2 = np.zeros((N,D+3))
    X2[:, 0:(D-1)] = X[:, 0:(D-1)]
    
    for n in range(N ):
        t = int(X[n, D-1])
        X2[n,t+D-1] = 1
    
    Z = np.zeros((N,4))
    Z[np.arange(N),X[:,D-1].astype(np.int32)] = 1
    assert(np.abs(X2[:,-4:] -Z).sum()< 10e-10)
    return X2,Y

def get_binaray_data():
    X,Y = get_data()
    X2 = X[Y<=1]
    Y2 = Y[Y<=1]
    return X2,Y2

In [65]:
df = pd.read_csv('./data/ecommerce_data.csv')

df.head()

is_mobile  n_products_viewed  visit_duration  is_returning_visitor  \
0          1                  0        0.657510                     0   
1          1                  1        0.568571                     0   
2          1                  0        0.042246                     1   
3          1                  1        1.659793                     1   
4          0                  1        2.014745                     1   

   time_of_day  user_action  
0            3            0  
1            2            1  
2            1            0  
3            1            2  
4            1            2

In [66]:
get_data()

(array([[ 1.        , -0.81697841, -0.40827769, ...,  0.        ,
          0.        ,  1.        ],
        [ 1.        ,  0.13967078, -0.4994283 , ...,  0.        ,
          1.        ,  0.        ],
        [ 1.        , -0.81697841, -1.03884323, ...,  1.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        , -0.81697841, -0.90498762, ...,  0.        ,
          0.        ,  1.        ],
        [ 1.        , -0.81697841, -0.86695367, ...,  0.        ,
          0.        ,  1.        ],
        [ 0.        , -0.81697841,  1.59982383, ...,  0.        ,
          0.        ,  1.        ]]),
 array([0., 1., 0., 2., 2., 2., 0., 0., 1., 0., 3., 0., 0., 1., 0., 3., 1.,
        1., 1., 0., 2., 0., 0., 3., 0., 1., 0., 0., 2., 2., 0., 1., 2., 2.,
        1., 0., 0., 1., 1., 0., 2., 1., 0., 1., 3., 0., 1., 0., 0., 1., 2.,
        3., 1., 2., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
        1., 1., 0., 0., 0., 0., 0., 0., 1., 2., 0., 2., 0., 0., 0., 0

In [67]:
X,Y = get_binaray_data()

In [68]:
D = X.shape[1]
W = np.random.randn(D)
b = 0

In [69]:
def sigmod(a):
    return 1/(a+np.exp(-1))

def forward(X,W,b):
    return sigmod(X.dot(W)+b)

In [70]:
P_Y_given_X = forward(X,W,b)
P_Y_given_X

array([ 2.07368874e-01,  2.25973136e-01,  1.64345363e-01,  1.54207930e+00,
        1.74180936e-01, -6.58065671e-01,  6.34920606e-01,  9.90193645e-01,
        2.58952004e-01,  2.18807751e-01,  8.00319344e-01,  2.65050331e-01,
        2.39798456e-01,  4.95662465e-01,  4.64671158e-01,  3.47247291e+00,
        2.31366563e-01,  5.28198988e-01,  7.08670406e-01, -2.36131833e+01,
        4.63461484e-01,  2.04519773e-01, -6.81083643e-01, -1.68706827e+00,
        1.73232510e-01,  6.40452287e-01,  3.19603135e-01,  5.60393094e-01,
        9.92807229e-01,  2.73797662e-01,  2.23887938e+00,  3.90836891e+00,
       -4.69202833e+00,  1.03170231e+01,  1.65764777e-01, -2.15803206e+00,
        2.14873363e-01,  1.02249061e+00,  2.94987995e-01,  2.07600122e-01,
       -5.88475511e-01,  4.83322919e-01,  2.50036911e-01,  6.68184941e-01,
        2.62997017e-01,  1.89413502e+00, -3.48729978e+00,  2.20918322e-01,
       -4.79481128e-01,  7.58988813e-01,  3.00326911e-01,  3.30432602e-01,
        2.40465659e-01, -

In [71]:
predictions = np.round(P_Y_given_X)
predictions

array([  0.,   0.,   0.,   2.,   0.,  -1.,   1.,   1.,   0.,   0.,   1.,
         0.,   0.,   0.,   0.,   3.,   0.,   1.,   1., -24.,   0.,   0.,
        -1.,  -2.,   0.,   1.,   0.,   1.,   1.,   0.,   2.,   4.,  -5.,
        10.,   0.,  -2.,   0.,   1.,   0.,   0.,  -1.,   0.,   0.,   1.,
         0.,   2.,  -3.,   0.,  -0.,   1.,   0.,   0.,   0., -68.,  -0.,
         0.,   0.,   0.,  -4.,   0.,   0.,   0.,  11.,   1.,   1.,   0.,
         3.,   0., 177.,  -0.,   0.,   2.,   0.,  -1.,  -1.,   4.,   2.,
         0.,   0.,   0.,   1.,  -0.,  -1.,  -8.,   0.,   0.,   0.,  -1.,
         0.,   0.,   0.,   1.,   0.,   0.,  -1.,   0.,   1.,  35.,   3.,
         1.,   3.,   3.,   1.,   1.,   1.,   0.,  32.,  -0.,   0.,   0.,
         0.,   0.,   0.,   1.,   1.,   1.,   0.,   0.,  -1.,   4.,   0.,
         0.,  -1.,   1.,   0.,   0.,   2.,   1.,   0.,   1.,   1.,  -2.,
        -0.,  -3.,   0.,   1.,   0.,   0.,   0.,  -3.,   0.,   0.,   2.,
         0.,   0.,   1.,   0.,   3.,   0.,  -0.,   

In [72]:
def classifyication_rates(Y,P):
    return np.mean(Y==P)


In [73]:
print( "Scores", classifyication_rates(Y,predictions))



Scores 0.41959798994974873
