In [50]:
import numpy as np
import torch
torch.cuda.is_available()

True

In [51]:
torch.empty(5,3)

tensor([[-6.0995e-11,  3.0672e-41,  0.0000e+00],
        [ 0.0000e+00,  5.4697e-01, -1.1050e+00],
        [-1.8716e-01, -8.0993e-01,  1.3501e-01],
        [ 6.6838e-02,  8.5272e-01, -1.2543e+00],
        [-5.2283e-01, -7.2298e-02,  9.8813e-01]])

In [52]:
torch.rand(5,3)

tensor([[0.7241, 0.2502, 0.6927],
        [0.7585, 0.2711, 0.2594],
        [0.1502, 0.7634, 0.8718],
        [0.9990, 0.9267, 0.8149],
        [0.8996, 0.4331, 0.9745]])

In [53]:
torch.zeros(5,3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [54]:
torch.tensor([5.5,3])

tensor([5.5000, 3.0000])

In [55]:
x = torch.ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [56]:
torch.randn_like(x,dtypeze=torch.float)

TypeError: randn_like() received an invalid combination of arguments - got (Tensor, dtypeze=torch.dtype), but expected one of:
 * (Tensor input, torch.dtype dtype, torch.layout layout, torch.device device, bool requires_grad)
 * (Tensor input, bool requires_grad)
      didn't match because some of the keywords were incorrect: dtypeze


In [57]:
x = torch.randn(1)
print(x)


tensor([1.1655])


In [58]:
x.item()

1.1655058860778809

In [59]:
a = torch.ones(5)
print(a)
a.dtype

tensor([1., 1., 1., 1., 1.])


torch.float32

In [60]:
b = a.numpy()
print(b)
b

[1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1.], dtype=float32)

In [61]:
a.add_(1)
print(b)
a

[2. 2. 2. 2. 2.]


tensor([2., 2., 2., 2., 2.])

## Converting NumPy Array to Torch Tensor

In [62]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [63]:
x = torch.ones(2,3,requires_grad=True)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [64]:
y = x+2
y

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)

In [65]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward1>)


In [66]:
out.backward()

In [67]:
print(x.grad)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
